### ISSUE TITLE
Loading custom data from ArrayList

### ISSUE THREAD

**Issue by seveli** [saber-solooki/StickyHeader#5]
Hello, i'm trying to use this library to make a header/list by adding custom data from ArrayList. 
But i'm finding it a bit unclear, can anyone help me with this issue?

**Comment by IexeDev** [comment]
Well
First, check this link 

https://gist.github.com/saber-solooki/edeb57be63d2a60ef551676067c66c71?source=post_page---------------------------

There is an example, take a look on the class Adapter constructor, he is initializing some sort of example class to fill the recyclerview.

You can do the same with your own Arraylist, just build it from the activity or fragment and them put it from the constructor

Hope this can help you, but you can share a piece of your code so we can help.

Greattings
